name: horang_print
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_esc_pos_utils: ^1.0.1

  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  get_it: ^8.0.3
  dio: ^5.8.0
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  shadcn_ui: ^0.15.0
  carousel_slider: ^5.0.0
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  image: ^4.3.0
  dotted_box: ^0.0.3
  loading_animation_widget: ^1.3.0
  pretty_qr_code: ^3.5.0
  google_fonts: ^6.3.0
  cached_network_image: ^3.4.1

  flutter_sewoo_usb_printer:
    path: ./packages/flutter_sewoo_usb_printer


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sample_images/
    - assets/logo/
    - .env
